<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class MedecinEditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->remove('image');
    }

    public function getParent()
    {
        return MedecinType::class; // TODO: Change the autogenerated stub
    }
}
