<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class UserEditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->remove('enabled')
            ->remove('allRoles');
    }

    public function getParent()
    {
        return UserType::class; // TODO: Change the autogenerated stub
    }
}
